# Generated by Django 5.1.4 on 2024-12-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_id',
            new_name='product_id',
        ),
    ]
