# Generated by Django 5.1.4 on 2025-01-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_product_id_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
