# Generated by Django 5.1.4 on 2024-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=12)),
            ],
        ),
    ]
