# Generated by Django 5.1.4 on 2024-12-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_product_id_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
